version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: raqed_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raqeb
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7
    container_name: raqeb_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
